export const getImageForRatio = (name: string): string => {
    switch (name) {
        case "Fer":
            return "./productions/fer.png";
        case "Planche":
            return "./productions/Planche.png";
        case "Bois":
            return "./productions/bois.png";
        case "Charbon":
            return "./productions/charbon.png";
        case "Vitrerie":
            return "./productions/vitrerie.png";
        case "Silice":
            return "./productions/silice.png";
        case "Fourneaux":
            return "./productions/barredefer.png";
        case "Fenetre":
            return "./productions/fenetre.png";
        case "Cochons":
            return "./productions/cochon.png";
        case "Ferme de blé":
            return "./productions/ble.webp";
        case "Fourrure":
            return "./productions/fourrure.png";
        case "R-Coton":
            return "./productions/coton.png";
        case "Coton":
            return "./productions/plantationcotton.png";
        case "Calcaire":
            return "./productions/calcaire.png";
        case "Ciment":
            return "./productions/ciment.png";
        case "Laiton":
            return "./productions/laiton.png";
        case "Zinc":
            return "./productions/zinc.png";
        case "Cuivre":
            return "./productions/cuivre.png";
        case "Salpetre":
            return "./productions/salpetre.webp";
        case "saucisse":
            return "./productions/saucisse.png";
        case "Caoutchou":
            return "./productions/caoutchou.webp";
        case "Lingots":
            return "./productions/lingot.png";
        case "Or":
            return "./productions/or.png";
        case "Raisin":
            return "./productions/raisin.png";
        case "Perles":
            return "./productions/perles.png";
        case "Marqueterie":
            return "./productions/marquetterie.png";
        case "Véhicules":
            return "./productions/vehicule.png";
        case "Roue":
            return "./productions/roue.png";
        case "Gramophone":
            return "./productions/gramophone.png";
        case "Bijoux":
            return "./productions/bijoux.png";
        case "Montres":
            return "./productions/montre.png";
        case "Champagne":
            return "./productions/champagne.webp";
        case "Boulangerie":
            return "./productions/boulangerie.png";
        case "Ampoules":
            return "./productions/ampoule.png";
        case "Filament":
            return "./productions/filament.png";
        case "Moteur":
            return "./productions/moteur.png";
        case "Cycle":
            return "./productions/cycle.png";
        case "Moulin":
            return "./productions/farine.png";
        case "mouton":
            return "./productions/mouton.png";
        case "mouton":
            return "./productions/mouton.png";
        case "brique":
            return "./productions/brique.png";
        case "argile":
            return "./productions/argile.png";
        case "schnapps":
            return "./productions/schnapps.png";
        case "pommedeterre":
            return "./productions/pommedeterre.png";
        case "Brasserie":
            return "./productions/brasserie.png";
        case "Arme":
            return "./productions/armes.webp";
        case "Houblon":
            return "./productions/houblon.png";
        case "Malterie":
            return "./productions/malterie.webp";
        case "Usines":
            return "./productions/metallerie.png";
        case "Savonnerie":
            return "./productions/savonnerie.png";
        case "Render":
            return "./productions/render.png";
        case "Conserve":
            return "./productions/conserve.webp";
        case "Cuisine":
            return "./productions/cuisine.png";
        case "Boeuf":
            return "./productions/boeuf.png";
        case "Poivrons":
            return "./productions/poivrons.png";
        case "Machine":
            return "./productions/machine.png";
        case "Vetement":
            return "./productions/vetement.png";
        case "Lunettes":
            return "./productions/lunette.png";
        case "vetementsdetravail":
            return "./productions/vetementsdetravail.png";
        case "Armes_lourdes":
            return "./productions/armeslourdes.png";
        case "Dynamite":
            return "./productions/dynamite.png";
        default:
            return "";
    }
};
